---
name: test-ipa-ipa-trust
run-name: Test IPA-IPA trust
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Debug environment
        run: |
          id
          cat /proc/$$/subuid_map ||:
          cat /proc/$$/subgid_map ||:
          cat /etc/subuid ||:
          cat /etc/subgid ||:

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install libkrb5-dev libvirt-dev
          sudo apt install software-properties-common
          sudo apt install ansible podman

      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: containerfile-fedora
          tags: latest
          containerfiles: ipalab-config/ipa-trust/containerfile-fedora

      - name: Setup ipalab config
        run: |
          python3 -m venv venv
          source venv/bin/activate
          cd ipalab-config/ipa-trust
          pip3 install -r requirements.txt
          pip3 install podman-compose

      - name: Generate containers
        run: |
          source venv/bin/activate
          pushd ipalab-config/ipa-trust
          ipalab-config ipalab-idmtoidm-trust.yaml
          mv ./idm2idm-trust ../..
          popd
          cd ./idm2idm-trust
          podman-compose -f compose.yml up -d
          ansible-galaxy collection install \
                         -r requirements.yml

      - name: Create IPA deployments
        run: |
          source venv/bin/activate
          cd ./idm2idm-trust
          # disable 'become' on install-clupster.yml playbook
          sed -i 's/become: .*$/become: false/' \
              ${HOME}/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/playbooks/install-cluster.yml
          ansible-playbook -i inventory.yml \
                           ${HOME}/.ansible/collections/ansible_collections/freeipa/ansible_freeipa/playbooks/install-cluster.yml

      - name: Establish trust between IPA deployments
        run: |
          source venv/bin/activate
          ansible-galaxy collection install ansible.posix
          cd ./idm2idm-trust
          ansible-playbook -i inventory.yml \
                           playbooks/establish-trust.yaml \
                           -e on_github_workflow=true
...
